# Credenciales Sentinel Hub
SENTINELHUB_INSTANCE_ID = "PLAK81593ed161694ad48faa8065411d2539"
SENTINELHUB_CLIENT_ID = "23729a0d-75f6-478b-8304-c8bb2bfbe71d"
SENTINELHUB_CLIENT_SECRET = "854eeebf-f870-484a-96f4-d23d49b5f071"
